export interface Seafarer {
    Id: number;
    KinName: string | null;
    KinPhone: string | null;
    KinEmail: string | null;
    PassPortIssueDate: string | null;
    EmpId: number;
    VisaSponsorId: number;
    Remarks: string | null;
    VisaIssueDate: string | null;
    VisaExpiryDate: string | null;
    EmployeeName: string;
    SponsorName: string;
    EmployeeCode: string;
    JobName: string;
    Nationality: string;
    BirthDate: string | null;
    Phone: string | null;
    Mobile: string | null;
    Email: string | null;
    NationalId: string | null;
    EmploymentDate: string | null;
    InsuranceDate: string | null;
    PassportExpireDate: string | null;
    PassportNumber: string;
    Age: string;
    EmployeeNameAR: string;
    EmployeeNameEN: string;
    JobNameEN: string;
    JobNameAR: string;
    Salary: number;
    Address: string | null;
    Gender: string | null;
    Religion: string | null;
    InsuranceNumber: string | null;
    Area: string | null;
    MilitaryServiceExpireDate: string | null;
    SyndicateCardNumber: string | null;
    SyndicateExpirationDate: string | null;
    BusinessPhone: string | null;
    BirthPlace: string | null;
    NationalIdExpiryDate: string | null;
    Company: string | null;
    WorkPermit: string | null;
    PermitNumber: string | null;
    BloodType: string | null;
    WorkLocation: string | null;
    PermitExpirationDate: string | null;
    Notes: string | null;
    MedicalInsuranceAmount: number | null;
    InsuranceTitle: string | null;
    InsuranceOffice: string | null;
    MedicalInsuranceNo: string | null;
    MedicalInsuranceDate: string | null;
    GraduationYear: string | null;
    PostGraduateDegree: string | null;
    PostGraduateUniversity: string | null;
    PostGraduateSpecialty: string | null;
    PostGraduateGrade: string | null;
    PropationEndDate: string | null;
    EmpManager: string | null;
    NameOfSpouse: string | null;
    NoOfChildren: number | null;
    BodyWeight: number | null;
    Height: number | null;
    VisaUAEIdNO: string | null;
    NearestAirport: string | null;
    ResidenceNumber: string | null;
    SkypeID: string | null;
    PermanentAddressHomeCountry: string | null;
    ContactNumberHomeCountry: string | null;
    ContactNameAndNumberDuringEmergenciesUAE: string | null;
    ContactNameAndNumberDuringEmergenciesHome: string | null;
    SeamanBookNO: string | null;
    SeamanIssueDate: string | null;
    SeamanExpiryDate: string | null;
    CicpaNO: string | null;
    CicpaIssueDate: string | null;
    CicpaExpiryDate: string | null;
    Declaration: string | null;
    SignedOffFromAShipDueToMedicalReason: boolean | null;
    SignedOffFromAShipDueToMedicalReasonComment: string | null;
    UndergoneAnyMdicalOperation: boolean | null;
    UndergoneAnyMdicalOperationComment: string | null;
    DoctorConsultation: boolean | null;
    DoctorConsultationComment: string | null;
    HealthOrDisabilityProblem: boolean | null;
    HealthOrDisabilityProblemComment: string | null;
    InquiryOrInvolvedMaritimeAccident: boolean | null;
    InquiryOrInvolvedMaritimeAccidentComment: string | null;
    LicenseSuspendedOrRevoked: boolean | null;
    LicenseSuspendedOrRevokedComment: string | null;
    ConfirmationInsuranceDate: string | null;
    MaritalStatus: string | null;
    Status: number;
}
